/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.washingmachineproject;

/**
 *
 * @author oaits
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton_Products = new javax.swing.JButton();
        jButton_Employees = new javax.swing.JButton();
        jButton_Customers = new javax.swing.JButton();
        jButton_Queries = new javax.swing.JButton();
        jButton_logout = new javax.swing.JButton();
        jPanel_purchase = new javax.swing.JPanel();
        jLabel_purchase = new javax.swing.JLabel();
        jComboBox_customer = new javax.swing.JComboBox<>();
        jComboBox_product = new javax.swing.JComboBox<>();
        jButton_purchase = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menu");

        jButton_Products.setText("Products");
        jButton_Products.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ProductsActionPerformed(evt);
            }
        });

        jButton_Employees.setText("Employees");
        jButton_Employees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EmployeesActionPerformed(evt);
            }
        });

        jButton_Customers.setText("Customers");
        jButton_Customers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CustomersActionPerformed(evt);
            }
        });

        jButton_Queries.setText("Queries");
        jButton_Queries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_QueriesActionPerformed(evt);
            }
        });

        jButton_logout.setText("Logout");
        jButton_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_logoutActionPerformed(evt);
            }
        });

        jPanel_purchase.setBackground(new java.awt.Color(153, 153, 255));
        jPanel_purchase.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel_purchase.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_purchase.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_purchase.setText("Purchase");

        jComboBox_customer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox_product.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton_purchase.setText("Purchase");

        javax.swing.GroupLayout jPanel_purchaseLayout = new javax.swing.GroupLayout(jPanel_purchase);
        jPanel_purchase.setLayout(jPanel_purchaseLayout);
        jPanel_purchaseLayout.setHorizontalGroup(
            jPanel_purchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_purchaseLayout.createSequentialGroup()
                .addGroup(jPanel_purchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_purchaseLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel_purchase))
                    .addGroup(jPanel_purchaseLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel_purchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox_customer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox_product, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_purchase, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel_purchaseLayout.setVerticalGroup(
            jPanel_purchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_purchaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_purchase)
                .addGap(18, 18, 18)
                .addComponent(jComboBox_customer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox_product, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButton_purchase)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton_Queries, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_Employees, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                .addComponent(jButton_Products, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_Customers, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel_purchase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jButton_Customers)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Products)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Employees)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Queries))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel_purchase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jButton_logout)
                .addGap(0, 36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ProductsActionPerformed
        //Creating New Window Menu
        ProductMenu frame = new ProductMenu();
        frame.setVisible(true);
        frame.pack();
        frame.setLocationRelativeTo(null);
                
        //Closing current Window
        this.dispose();
    }//GEN-LAST:event_jButton_ProductsActionPerformed

    private void jButton_EmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EmployeesActionPerformed
        //Creating New Window Menu
        EmployeeMenu frame = new EmployeeMenu();
        frame.setVisible(true);
        frame.pack();
        frame.setLocationRelativeTo(null);
                
        //Closing current Window
        this.dispose();
    }//GEN-LAST:event_jButton_EmployeesActionPerformed

    private void jButton_QueriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_QueriesActionPerformed
        //Creating New Window Menu
        QueryMenu frame = new QueryMenu();
        frame.setVisible(true);
        frame.pack();
        frame.setLocationRelativeTo(null);
                
        //Closing current Window
        this.dispose();
    }//GEN-LAST:event_jButton_QueriesActionPerformed

    private void jButton_CustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CustomersActionPerformed
        //Creating New Window Menu
        CustomerMenu frame = new CustomerMenu();
        frame.setVisible(true);
        frame.pack();
        frame.setLocationRelativeTo(null);
                
        //Closing current Window
        this.dispose();
    }//GEN-LAST:event_jButton_CustomersActionPerformed

    private void jButton_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_logoutActionPerformed
        WashingMachineFrame frame = new WashingMachineFrame();
        frame.setVisible(true);
        frame.pack();
        frame.setLocationRelativeTo(null);
                
        //Closing current Window
        this.dispose();
    }//GEN-LAST:event_jButton_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Customers;
    private javax.swing.JButton jButton_Employees;
    private javax.swing.JButton jButton_Products;
    private javax.swing.JButton jButton_Queries;
    private javax.swing.JButton jButton_logout;
    private javax.swing.JButton jButton_purchase;
    private javax.swing.JComboBox<String> jComboBox_customer;
    private javax.swing.JComboBox<String> jComboBox_product;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_purchase;
    private javax.swing.JPanel jPanel_purchase;
    // End of variables declaration//GEN-END:variables
}
